# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Producer Organization
  # ---------------------------------------------------------------------------
  - Name: Producer
    Domain: producer.example.com
    EnableNodeOUs: true
    Template:
      Count: 2  # Two peers
      SANS:
        - localhost
    Users:
      Count: 1  # One user
