# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'
services:
  # Orderer nodes
  orderer1.example.com:
    container_name: orderer1.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_LOCAL_MSP_CONFIG_PATH=/var/hyperledger/orderer/msp
    ports:
      - "7050:7050"
    volumes:
      - ./docker/orderercfg:/var/hyperledger/orderer

  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_LOCAL_MSP_CONFIG_PATH=/var/hyperledger/orderer/msp
    ports:
      - "8050:8050"
    volumes:
      - ./docker/orderercfg:/var/hyperledger/orderer

  orderer3.example.com:
    container_name: orderer3.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_LOCAL_MSP_CONFIG_PATH=/var/hyperledger/orderer/msp
    ports:
      - "9050:9050"
    volumes:
      - ./docker/orderercfg:/var/hyperledger/orderer

  # Producer Organization
  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer0.producer.example.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    ports:
      - "7051:7051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  peer1.producer.example.com:
    container_name: peer1.producer.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer1.producer.example.com:8051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    ports:
      - "8051:8051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  # Supplier Organization
  peer0.supplier.example.com:
    container_name: peer0.supplier.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer0.supplier.example.com:9051
      - CORE_PEER_LOCALMSPID=SupplierMSP
    ports:
      - "9051:9051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  peer1.supplier.example.com:
    container_name: peer1.supplier.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer1.supplier.example.com:10051
      - CORE_PEER_LOCALMSPID=SupplierMSP
    ports:
      - "10051:10051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  # Wholesaler Organization
  peer0.wholesaler.example.com:
    container_name: peer0.wholesaler.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer0.wholesaler.example.com:11051
      - CORE_PEER_LOCALMSPID=WholesalerMSP
    ports:
      - "11051:11051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  peer1.wholesaler.example.com:
    container_name: peer1.wholesaler.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ADDRESS=peer1.wholesaler.example.com:12051
      - CORE_PEER_LOCALMSPID=WholesalerMSP
    ports:
      - "12051:12051"
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg

  # CLI container
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
